### ISSUE TITLE
Protocol update effort (tracking issue)

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/specification#2]
This is an attempt of gathering references to everything concerned by the new protocol. The list will be edited to be kept updated. To keep this issue helpfull instead of just becoming yet another place to discuss things, please keep specialized discussion in the relevant issue.

### Administriva

 - [x] Settle on how to do versioning and stabilization
     - https://github.com/UAVCAN/uavcan.github.io/issues/39

### Core protocol

 - [x] Decide what to do with TAO
     - TAO as a concept will be removed entirely for the new protocol. (https://github.com/UAVCAN/uavcan.github.io/issues/34)
 - [x] Decide how ID fields should look like
     - ID fields will look like the following: https://github.com/UAVCAN/dsdl/issues/35#issuecomment-412284222
 - [x] Decide how dsdl version info should be conveyed over the wire
    - The dsdl major version number will be put in the ID field: https://github.com/UAVCAN/dsdl/issues/35#issuecomment-412284222
 - [x] Decide where the tail byte should be put in the existence of padding
     - The tail byte should always be put on the DLC boundary (https://github.com/UAVCAN/uavcan.github.io/issues/35)
 - [x] Decide where CRC should be put in the existence of padding
     - The CRC should be put directly before the tail-byte and directly after the padding bytes (https://github.com/UAVCAN/uavcan.github.io/issues/36)
 - [x] Settle on whether CRC should include data type signature (or other forms of compatibility analyzis).
     - Transfer CRC should not include any compatibility checks
 - [x] Settle on how the protocol version should be conveyed over the wire
     - Initial value of the toggle bit and a designated bit in the CAN ID (for CAN transports)

### DSDL

 - [x] What to do with the old compatibility concepts (normalization and dsdl signatures)
     - Signatures and normalization will be removed as a concept.
 - [x] Figure out how we handle deprecations of definitions.
     - Directive `@deprecated` (#10)
 - [x] Figure out if we should do anything to namespacing of dsdl
     - Domain-specific namespaces are considered unnecessary #3 
 - [x] Figure out what limitations we should put on code compatibility
     - Follow the discussion (https://github.com/UAVCAN/specification/issues/9)

**Comment by kjetilkjeka** [comment]
@pavel-kirienko feel free to add/edit stuff, or uncheck things if i were to quick to check them.

**Comment by pavel-kirienko** [comment]
I marked the TAO entry as decided since the consensus seems to be in favor of its complete removal. Bye bye TAO.

**Comment by kjetilkjeka** [comment]
> Settle on whether CRC should include data type signature (or other forms of compatibility analyzis).

I think we've practically reached consensus on that the CRC should not include data type signatures or similar. Check off your ticky box if you agree to the conclusion and that the discussion has been left open long enough. Or edit and add another ticky box if you want to bring the attention to someone else.

 - [ ] @kjetilkjeka 
 - [ ] @thirtytwobits 
 - [ ] @pavel-kirienko

**Comment by pavel-kirienko** [comment]
> It has been suggested to use a bit in the transfer ID, but the current discussion is leaning towards not conveying protocol version info over the wire.

I think the discussion is leaning towards using the toggle bit for that. I took the liberty to reflect that in the draft (sec 4.2.3.2), believing that that was the consensus:

> Transfers where the initial value of the toggle bit is zero must be ignored. The initial state of the toggle bit may be inverted in the future revisions of the protocol to facilitate automatic protocol version detection.

**Comment by kjetilkjeka** [comment]
Yes you're absolutely right. Thanks for pointing this out, I've updated the overview now.

**Comment by pavel-kirienko** [comment]
Marked the following as resolved:

- Settle on how the protocol version should be conveyed over the wire
- Figure out how we handle deprecations of definitions.
- Figure out if we should do anything to namespacing of dsdl

**Comment by pavel-kirienko** [comment]
All important things have been settled upon and resolved, so I am closing this. For future reference, many important decisions have been discussed there: https://forum.uavcan.org/c/dev
