### ISSUE TITLE
Specification update effort (tracking issue)

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/specification#42]
- [x] Finalize the DSDL chapter (№3). Relevant context: https://forum.uavcan.org/t/new-dsdl-directive-for-simple-compile-time-checks/190/ and https://forum.uavcan.org/t/data-type-compatibility-assurance/196/. Also, see https://github.com/UAVCAN/specification/pull/33
- [x] Finalize the Application layer chapter (№5). See #29, #30, #22 .
- [x] Add a chapter listing definitions of all standard data types. This one is easy, no writing required.
- [x] Restructure the contents (requires all chapters to be finished first). Make the transport chapter structure compatible with alternative transports. Some content may need to be moved around the document to make its overall structure more sensible.
- [x] Proofread the whole doc #41
